- hosts: all
  become: true
  handlers:
    - name: restart frr
      service:
        name: frr
        state: restarted

    - name: add ip address on br100
      shell: ip addr add {{ br100_ip }} dev br100

  tasks:
    - name: set ips
      set_fact:
        self_ip: "{{ ansible_all_ipv4_addresses | ipaddr('10.255.255.0/24') |first }}"
        br100_ip: "{{ br100_ips[inventory_hostname] }}"
      vars:
        br100_ips:
          vxlan-1: 172.16.0.1/24
          vxlan-2: 172.16.0.2/24

    - name: add frr apt key
      apt_key:
        url: https://deb.frrouting.org/frr/keys.asc
        state: present

    - name: add frr repositroy
      apt_repository:
        filename: frr
        repo: "deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable"
        state: present

    - name: apt update cache
      apt:
        update_cache: true

    - name: install frr
      apt:
        name:
          - frr
          - frr-pythontools

    - name: install bridge-utils
      apt:
        name: bridge-utils
        state: present

    - name: ensure frr service is started
      service:
        name: frr
        enabled: true
        state: started

    - name: enable bgpd
      lineinfile:
        path: /etc/frr/daemons
        regexp: '^bgpd='
        line: bgpd=yes
      notify:
        restart frr

    - name: flush handlers
      meta: flush_handlers

    - name: add evpn config
      shell: |
        vtysh -c 'configure terminal
          router bgp 65000
            bgp router-id {{ self_ip }}
            no bgp default ipv4-unicast
            neighbor fabric peer-group
            neighbor fabric remote-as 65000
            neighbor fabric capability extended-nexthop
            {% for ipaddress in ['10.255.255.101', '10.255.255.102'] | difference(ansible_all_ipv4_addresses | ipaddr('10.255.255.0/24')) %}
            neighbor {{ ipaddress }} peer-group fabric
            {% endfor %}
            address-family l2vpn evpn
              neighbor fabric activate
              advertise-all-vni
            exit-address-family
            end
        write memory'

    - name: create vxlan100
      shell: |
        ip link add vxlan100 type vxlan id 100 dstport 4789 local {{ self_ip }} nolearning
        brctl addbr br100
        brctl addif br100 vxlan100
        brctl stp br100 off
        ip link set up dev br100
        ip link set up dev vxlan100

    - name: get ip address on br100
      shell: "ip addr list dev br100 | grep -F {{ br100_ip }}"
      register: ip_output
      changed_when: ip_output.stdout == ''
      failed_when: false
      notify: add ip address on br100
